### ISSUE TITLE
less url bugs

### ISSUE THREAD

**Issue by exomarty** [MegaGM/nodebb-plugin-mega-colors#2]
https://github.com/MegaGM/nodebb-plugin-mega-colors/blob/master/lib/colorpicker/css/colorpicker.less#L6

is pointing to bad path and plugin name

**Comment by MegaGM** [comment]
Thank you very much! I'll fix it as soon as I will be at home.

**Comment by exomarty** [comment]
pinging this :dancer: 
if you dont have time i can try solve it

![screenshot_12](https://cloud.githubusercontent.com/assets/10746278/18465069/06166c3a-7995-11e6-9ba6-37c26ffe9502.png)
